In [1]:
NAME = "Min Cheah"

---

# Lab 6: Skip Gram

**Please read the following instructions very carefully**

## Working on the assignment / FAQs
- **Always use the seed/random_state as *42* wherever applicable** (This is to ensure repeatability in answers, across students and coding environments)
- The type of question and the points they carry are indicated in each question cell
- To avoid any ambiguity, each question also specifies what *value* must be set. Note that these are dummy values and not the answers
- If an autograded question has multiple answers (due to differences in handling NaNs, zeros etc.), all answers will be considered.
- You can delete the `raise NotImplementedError()`
- **Submitting the assignment** : Download the '.ipynb' file from Colab and upload it to bcourses. Do not delete any outputs from cells before submitting.
- That's about it. Happy coding!


Available software:
 - Python's Gensim module: https://radimrehurek.com/gensim/ (install using pip)

_Note: The most important hyper parameters of skip-gram/CBOW are vector size and windows size_


In [2]:
!pip install gensim
import pandas as pd
import numpy as np
import gensim

In [3]:
import gensim.downloader as api

model = api.load('word2vec-google-news-300') # this step might take ~10-15 minutes

[==================================================] 100.0% 1662.8/1662.8MB downloaded


### **Q1 (1 point)**
Find the cosine similarity between the following word pairs
- (President, Election)
- (Hot, Warm)
- (England, London)
- (France, ball)
- (small, smaller)

In [4]:
#Replace 0 with the code / value; Do not delete this cell
similarity_pair1 = model.similarity('President', 'Election')
similarity_pair2 = model.similarity('Hot', 'Warm')
similarity_pair3 = model.similarity('England', 'London')
similarity_pair4 = model.similarity('France', 'ball')
similarity_pair5 = model.similarity('small', 'smaller')

In [5]:
#This is an autograded cell, do not edit/delete
print(similarity_pair1, similarity_pair2, similarity_pair3, similarity_pair4, similarity_pair5)

0.17330882 0.42109647 0.43992856 -0.010858273 0.6194288


### **Q2 (1 point)**
Write an expression to extract the vector representations of the words:

- France
- England
- smaller
- bigger
- rocket
- big

Get only the first 5 elements for each vector representation.

In [6]:
#Replace 0 with the code / value to get the first 5 elements of each vector; Do not delete this cell
vector_1 = model['France'][:5]
vector_2 = model['England'][:5]
vector_3 = model['smaller'][:5]
vector_4 = model['bigger'][:5]
vector_5 = model['rocket'][:5]
vector_6 = model['big'][:5]

In [7]:
#This is an autograded cell, do not edit/delete
print(vector_1)
print(vector_2)
print(vector_3)
print(vector_4)
print(vector_5)
print(vector_6)


[0.04858398 0.07861328 0.32421875 0.03491211 0.07714844]
[-0.19824219  0.11523438  0.0625     -0.05834961  0.2265625 ]
[-0.05004883  0.03417969 -0.0703125   0.17578125  0.00689697]
[-0.06542969 -0.09521484 -0.06225586  0.16210938  0.01989746]
[-0.03198242  0.27148438 -0.2890625  -0.15429688  0.16894531]
[ 0.11132812  0.10595703 -0.07373047  0.18847656  0.07666016]


### **Q3 (1 point)**
Find the euclidean distances between the word pairs :

- (France, England)
- (smaller, bigger)
- (England, London)
- (France, Rocket)
- (big, bigger)


In [8]:
#Replace 0 with the code / value; Do not delete this cell
eu_dist1 = np.linalg.norm(model['France'] - model['England'])
eu_dist2 = np.linalg.norm(model['smaller'] - model['bigger'])
eu_dist3 = np.linalg.norm(model['England'] - model['London'])
eu_dist4 = np.linalg.norm(model['France'] - model['Rocket'])
eu_dist5 = np.linalg.norm(model['big'] - model['bigger'])

In [9]:
#This is an autograded cell, do not edit / delete
print(eu_dist1)
print(eu_dist2)
print(eu_dist3)
print(eu_dist4)
print(eu_dist5)


3.0151067
1.8618743
2.8752837
3.892071
1.9586496


### **Q4 (1 point)**
Time to dabble with the power of Word2Vec. Find the 2 closest words  for the following conditions:  
- (King - Man + Queen)
- (bigger - big + small)
- (waiting - wait + run)
- (Texas + Milwaukee – Wisconsin)

Note: If your kernel crashes due to low memory and restarts, reload the model from the top and try running this part again.

In [10]:
#Replace 0 with the code / value; Do not delete this cell
closest1 = model.most_similar(positive=['King', 'Queen'], negative=['Man'], topn=2)
closest2 = model.most_similar(positive=['bigger', 'small'], negative=['big'], topn=2)
closest3 = model.most_similar(positive=['waiting', 'run'], negative=['wait'], topn=2)
closest4 = model.most_similar(positive=['Texas', 'Milwaukee'], negative=['Wisconsin'], topn=2)

In [11]:
#This is an autograded cell, do not edit/delete
print(closest1)
print(closest2)
print(closest3)
print(closest4)

[('Queen_Elizabeth', 0.5257916450500488), ('monarch', 0.5004087090492249)]
[('larger', 0.7402471303939819), ('smaller', 0.7329993844032288)]
[('running', 0.5654535889625549), ('runs', 0.49639999866485596)]
[('Houston', 0.7767744064331055), ('Fort_Worth', 0.7270511388778687)]


### **Q5 (3 points)**
Using the vectors for the words in the Google News dataset, apply K-means clustering (K=2) and find the top 5 most representative words/phrases of each cluster.

*Note: Since there are ~3Mil words in the vocabulary, you can downsample it to 25k randomly selected words*  \\
*Hint: The "similar_by_vector" method might be useful*

**Do not delete the below cell**

In [20]:
# Replace 0 with the code / value; Do not delete this cell
# YOUR CODE HERE
from sklearn.cluster import KMeans
import numpy as np
import random

random_words = random.sample(list(model.index_to_key), 25000)
word_vectors = np.array([model[word] for word in random_words])

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(word_vectors)
cluster_centers = kmeans.cluster_centers_

most_rep_cluster1 = model.similar_by_vector(cluster_centers[0], topn=5)
most_rep_cluster2 = model.similar_by_vector(cluster_centers[1], topn=5)

most_rep_cluster1 = [word[0] for word in most_rep_cluster1]  # Extract only words, not similarity scores
most_rep_cluster2 = [word[0] for word in most_rep_cluster2]

In [16]:
#This is an autograded cell, do not edit/delete
print(most_rep_cluster1)
print(most_rep_cluster2)

['http_dol##.net_index###.html_http', 'dol##.net_index####.html_http_dol##.net', 'index###.html_http_dol##.net_index###.html', 'Deltagen_undertakes', 'By_TRICIA_SCRUGGS']
['Emil_Protalinski_Published', 'By_QianMian_####-##-##', 'By_HuDie_####-##-##', 'By_XiaoBing_####-##-##', 'BY_GEOFF_KOHL']


### **Q6 (1 point)**
What loss function does the skipgram model use and briefly describe what this function is minimizing.

**Do not delete the below cell**

The Skip-gram model utilizes the negative sampling loss function that is targeted toward the goal of learning word embeddings in a very efficient manner by distinguishing between real context words-those which in general appear within proximity to the target word in text, and "negative" samples, randomly chosen not to do so. It works in such a way that it maximizes the probability of the target word being similar to its actual context words while minimizing its probability of being similar to negative samples. The computation becomes less complex because, instead of all the words, it concentrates on a few negative samples. Negative sampling allows fast training of the model, focusing on a few negative samples instead of all possible words, and still manages to capture meaningful relationships between words.








### **Bonus Question (1 point)**
Find at least 2 interesting word vec combinations like the ones given in Q4

**Do not delete the below cell**

In [17]:
# YOUR CODE HERE
interesting_comb1 = model.most_similar(positive=['Paris', 'Italy'], negative=['France'], topn=2)
interesting_comb2 = model.most_similar(positive=['Doctor', 'School'], negative=['Hospital'], topn=2)



In [19]:
print(interesting_comb1)
print(interesting_comb2)

[('Milan', 0.7222141623497009), ('Rome', 0.702830970287323)]
[('Flunked', 0.4351208508014679), ('teacher', 0.43253713846206665)]
